# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: blog.iproute.net
avatar: "/assets/images/icon_S.png"
email: keyvan@iproute.net
description: >- # this means to ignore newlines until "baseurl:"
    iproute.net is a Networking blog maintained by Keyvan Ghadimi.
    This blog is about my journey in the Networking world, I will share my lesson learned here.
twitter_username: iproutenet
github_username: iproute-net
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Keyvan Ghadimi"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Welcome to iproute.net blog.
            iproute.net is a Networking blog and it's  about my journey in the Networking world. I will write my lesson learned and study notes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.iproute.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Iproutenet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/iproute-net/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Iproutenet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/iproute-net/"


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all 
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "links"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "links"
  # _links
  - scope:
      path: ""
      type: links
    values:
      comments: true
      sidebar:
        nav: "links"
