# main.yml
name: adi blog on GitHub Pages

on: 
 push:
  branches:
   - master
  paths-ignore:
   - 'themes/adidoks/content/blog/**'
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.zola_token }}
